### PR TITLE
Update to latest recommended artifacts (5848)

### PR DESCRIPTION
**Pull request by Romariin**
Hello ! 👋
I didn't see the tag **5848** _(latest recommended artifacts)_ in https://hub.docker.com/r/spritsail/fivem/tags

This pull request may fixes the problem!
Have a nice day! 😎

### CODE REVIEW

**Comment by frebib** [comment]
We shouldn't roll back the master branch to an older version, but I do agree that we should have an automated build that tracks the `stable` (recommended) build versions.

For now, I've built 5848 based on your PR and pushed it to DH for you
https://hub.docker.com/layers/spritsail/fivem/5848/images/sha256-a5dd639689824d5195d193bf8508cd2587c5b947781105c555329976e6b6e0be?context=explore

We can look at adding those extra builds later. I hope this is sufficient for now. Let me know if not

**Comment by Romariin** [comment]
@frebib Perfect 👌
Thanks !

**Comment by Romariin** [comment]
Maybe there's a problem, the containers don't want to get started. (No errors logs)
image

image

**Comment by frebib** [comment]
139 is segmentation fault. I wonder if the data is incompatible like you say.
Is there any reason you want this really old build btw?

**Comment by Romariin** [comment]
> 139 is segmentation fault. I wonder if the data is incompatible like you say. Is there any reason you want this really old build btw?
There's no need, the recommended artifacts recently changed to 6683, and the build is in the tags [(here)](https://hub.docker.com/layers/spritsail/fivem/6683/images/sha256-b9c2daa99d5a6d2c1d62a62c0805b2ea0bfed6bf4e2abc477b8bb2be9adb9c89?context=explore).
Thanks a lot anyway for the help, and sorry to have bothered with this 😅

**Pull request closed without merging**
